---
- name: Change hostname
  hosts: all
  gather_facts: false
  tasks:
   - name: Merge the provided configuration with the existing running configuration
     cisco.nxos.nxos_hostname:
      config:
       hostname: NXOSv-9k
   - name: Merge provided configuration with device configuration.
     cisco.nxos.nxos_vlans:
      config:
       - vlan_id: 5
         name: test-vlan5
       - vlan_id: 10
         enabled: false
       state: merged    
  
