---
- name: Change Cisco NX-OS Hostname
  hosts: all
  gather_facts: no  # Disable gathering facts for network devices

  tasks:
    - name: Set the hostname
      nxos_system:
        hostname: "{{ new_hostname }}"
      vars:
        new_hostname: "NXOS01"  # Replace with the desired hostname
      register: result

    - name: Display the result
      debug:
        var: result
