---
- name: Change hostname
  hosts: all
  gather_facts: false
  tasks:
   - name: Merge the provided configuration with the existing running configuration
     cisco.nxos.nxos_hostname:
      config:
       hostname: NXOSv-9k
