---
- name: Change hostname
  hosts: all
  gather_facts: false
  tasks:
   - name: Apply the provided configuration
     cisco.ios.ios_hostname:
      config:
        hostname: NXOS-EXT01-01
      state: merged
