---
- name: Change Cisco Nexus switch hostname
  hosts: all
  gather_facts: no  # We don't need to gather facts for this task
  tasks:
    cisco.ios.ios_hostname:
    config:
      hostname: NXOS-EXT01-01
    state: merged
