---
- name: VLAN Config
  hosts: all
  gather_facts: false
  tasks:
  cisco.nxos.nxos_vlans:
    config:
    - vlan_id: 5
      name: test-vlan5
    - vlan_id: 10
      enabled: false
    state: merged
